language: python

python:
  - 2.6
  - 2.7
  - 3.4

env:

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - nosetests --with-cover --cover-package pandas_highcharts pandas_highcharts

after_success: coveralls
